name: Test Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Create aggregate tag env vars
      run: echo "Running the test workflow step testing again and again and again and again"