name: Test Workflow

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  release:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      RELEASE: test-release-24
    steps:
    - name: Release with asset
      run: |
        gh release create "$RELEASE" --repo=rpoet-jh/my-sandbox --generate-notes
        echo hello world sbom > application.cdx.json
        cp application.cdx.json my-test-$RELEASE-cyclonedx.json
        gh release upload "$RELEASE" --repo=rpoet-jh/my-sandbox my-test-$RELEASE-cyclonedx.json
