name: Test Workflow

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE: test-release-24
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Release with asset
      run: |
        gh release create "$RELEASE" --generate-notes
        echo hello world sbom > application.cdx.json
        cp application.cdx.json my-test-$RELEASE-cyclonedx.json
        gh release upload "$RELEASE" my-test-$RELEASE-cyclonedx.json
